// This string is autogenerated by ChangeAppSettings.sh, do not change spaces amount
package org.libsdl.app;

import android.app.Activity;
import android.content.Context;
import org.socool.pal.R;

class Globals {
	// This string is autogenerated by ChangeAppSettings.sh, do not change spaces amount
	public static String ApplicationName = "AndroidSDLPAL";

	// Should be zip file
	// This string is autogenerated by ChangeAppSettings.sh, do not change spaces amount
	public static String DataDownloadUrl = "http://apal.3322.org/pal.zip"; // This string is autogenerated by ChangeAppSettings.sh, do not change spaces amount

	// Set DownloadToSdcard to true if your app data is bigger than 5 megabytes.
	// It will download app data to /sdcard/alienblaster then,
	// otherwise it will download it to /data/data/de.schwardtnet.alienblaster/files -
	// set this dir in jni/Android.mk in SDL_CURDIR_PATH
	// This string is autogenerated by ChangeAppSettings.sh, do not change spaces amount
	public static boolean DownloadToSdcard = true;
	
	// Set this value to true if you're planning to render 3D using OpenGL - it eats some GFX resources, so disabled for 2D
	public static boolean NeedDepthBuffer = false;
}

class LoadLibrary {
	public LoadLibrary()
	{
		System.loadLibrary("tremor");
		System.loadLibrary("SDL");
		System.loadLibrary("SDL_mixer");
		System.loadLibrary("SDL_image");
		System.loadLibrary("SDL_ttf");
	}
}
